name: Creation of Dependent jobs 
on:
  push:
    branches:
      - main 
jobs:
  reviewJob:
   runs-on: ubuntu-latest
   steps:
    - name: review the code 
      run: echo "review the code"
  buildJob:
   runs-on: ubuntu-latest
   steps:
    - name: build the code 
      run: echo "Build the code"
  deployJob:
   needs: buildJob
   runs-on: ubuntu-latest
   steps:
    - name: Deploy the code 
      run: echo "Deploying..."
